"""Provider-agnostic assessment prompt scaffolding (Phase 3C.1 freeze).

The AI STRATEGY of the freeze: coding assessments use representative problems
(no AI). NON-coding assessments (quiz / behavioral / design / system_design)
will later be generated by an LLM, but this sprint only *prepares the
architecture* — it does NOT call any provider.

These templates:
  * receive a ``MissionContext`` + learner signals,
  * return a structured, provider-agnostic ``PromptSpec`` (system + user +
    variables + output schema),
  * hardcode NO provider (no Gemini/OpenAI/Claude), NO model, NO API call.

Actual LLM invocation is a later AI-integration phase; it will accept a
PromptSpec and produce questions.
"""
from .base import PromptSpec, PromptTemplate, get_prompt_template, PROMPT_REGISTRY  # noqa: F401
from . import templates as _templates  # noqa: F401  (registers builders)
